### ISSUE TITLE
sort attribute for default sorting doesn't work

### ISSUE THREAD

**Issue by charlyoleg2** [colinaut/action-table#15]
Thank you for this great component!
According to the documentation, the attribute 'sort' should define the default column to be used for sorting. In my case, no default sorting occurs. A snippet of my HTML:
```
<action-table sort="Type">
		<table>
			<caption>Design files</caption>
			<thead>
				<tr>
					<th>File</th>
					<th>Type</th>
					<th>Size</th>
```
Notice that when I click on the column 'Type', the sorting works properly.

**Comment by charlyoleg2** [comment]
By the way, the integration of action-table in [Astro](https://docs.astro.build/en/guides/client-side-scripts) works pretty well. If you need an example for the documentation: https://github.com/charlyoleg2/catalos/blob/main/pkg/catalui/src/components/DesiPosterFiles.astro

**Comment by colinaut** [comment]
Yeah you're right it's failing. I have some time today let me look into fixing that

**Comment by colinaut** [comment]
Fixed in latest release https://github.com/colinaut/action-table/releases/tag/2.4.20

Was an issue where if direction is not set it wouldn't run sort. Changed it to have direction default to 'ascending' if not set.

**Comment by colinaut** [comment]
Thanks for the bug report! And thanks for the Astro example!

**Comment by colinaut** [comment]
Thanks for the bug report! And thanks for the Astro example!

**Comment by charlyoleg2** [comment]
I have updated action-table to 2.4.20 and the default sort still doesn't work if there is only the attribute 'sort'.
If I add the attribute direction="ascending", then the default sort works.

**Comment by colinaut** [comment]
@charlyoleg2 oops forgot a step when releasing to NPM. Fixed now with latest release: https://github.com/colinaut/action-table/releases/tag/2.4.21

**Comment by charlyoleg2** [comment]
Thank you for your quick actions. I confirm it is fixed with 2.4.21
